### ISSUE TITLE
È possibile ordinare anche i prodotti marcati come "non ordinabili"

### ISSUE THREAD

**Issue by seldon** [madbob/GASdottoNG#81]
Marcando un prodotto del listino fornitore come "non ordinabile" ("Fornitori" -> tab "Prodotti" -> click sul prodotto da marcare -> switch 'Ordinabile' settato su 'OFF'), tale prodotto risulta poi comunque prenotabile (la casella per inserire la quantità è attiva e la prenotazione viene registrata).

Si tratta di un bug o di una scelta di design?

**Comment by pcdevoti** [comment]
Se la modifica avviene dopo che l’ordine era già stato aperto, è corretto così. Se si vuole eliminare il prodotto da un ordine aperto, va fatto con la funzione Ordini cliccando sulla casellina all’estrema sinistra nell’elenco dei prodotti. In questo modo, previa conferma, vengono anche annullate le prenotazioni eventualmente già inserite per quel prodotto.

 

Da: Lorenzo Franceschini <notifications@github.com> 
Inviato: mercoledì 20 marzo 2019 21:54
A: madbob/GASdottoNG <GASdottoNG@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Oggetto: [madbob/GASdottoNG] È possibile ordinare anche i prodotti marcati come "non ordinabili" (#81)

 

Marcando un prodotto del listino fornitore come "non ordinabile" ("Fornitori" -> tab "Prodotti" -> click sul prodotto da marcare -> switch 'Ordinabile' settato su 'OFF'), tale prodotto risulta poi comunque prenotabile (la casella per inserire la quantità è attiva e la prenotazione viene registrata).

Si tratta di un bug o di una scelta di design?

**Comment by seldon** [comment]
Ok, ho capito. 
Però, se posso permettermi una considerazione, l'affermazione *è corretto così* non mi convince affatto: diciamo piuttosto che si tratta di una scelta di design dell'applicazione, legittima ma soggettiva. 

Per come la vedo io, sarebbe più intuitivo che un prodotto marcato come "non ordinabile" (anche dopo l'apertura dell'ordine) non sia prenotabile da quel punto in poi.

My two cents ;-)

Ciao e grazie,
L.

**Comment by pcdevoti** [comment]
Come dici tu, questione di punti di vista 😊.

By design (ma non solo, la scelta deriva da quasi 10 anni di utilizzo di GASdotto nel nostro ed in altri GAS), nel momento in cui si apre un nuovo ordine, questo fotografa la situazione in quel momento e da quel momento in poi segue un percorso autonomo.

Di conseguenza variazioni di disponibilità dei prodotti fatte sul fornitore (in aggiunta o in eliminazione) NON si riflettono sull’ordine e viceversa; quindi il discorso vale sia per prodotti da eliminare dall’ordine sia per nuovi prodotti aggiunti sul fornitore che NON vengono automaticamente aggiunti all’ordine.

Nel caso di voglia aggiungere all’ordine un prodotto precedentemente non previsto, si clicca sul bottone “Tutti” in testa alla tabella dei prodotti ed a quel punto è possibile selezionare i prodotti da aggiungere all’ordine.

 

Ciao,

Pier Carlo

 

 

Da: Lorenzo Franceschini <notifications@github.com> 
Inviato: giovedì 21 marzo 2019 12:35
A: madbob/GASdottoNG <GASdottoNG@noreply.github.com>
Cc: pcdevoti <piercarlo.devoti@gmail.com>; Comment <comment@noreply.github.com>
Oggetto: Re: [madbob/GASdottoNG] È possibile ordinare anche i prodotti marcati come "non ordinabili" (#81)

 

Ok, ho capito.
Però, se posso permettermi una considerazione, l'affermazione è corretto così non mi convince affatto: diciamo piuttosto che si tratta di una scelta di design dell'applicazione, legittima ma soggettiva.

Per come la vedo io, sarebbe più intuitivo che un prodotto marcato come "non ordinabile" (anche dopo l'apertura dell'ordine) non sia prenotabile da quel punto in poi.

My two cents ;-)

Ciao e grazie,
L.

**Comment by seldon** [comment]
Grazie per i chiarimenti
Ciao,
L.
